export const SET_RESULTS = 'SET_RESULTS';
export const SET_HEADERS = 'SET_HEADERS';
export const SET_QUERY = 'SET_QUERY';
export const SET_FORMATTED_QUERY = 'SET_FORMATTED_QUERY';
export const SET_SEARCH_ERROR_MESSAGE = 'SET_SEARCH_ERROR_MESSAGE';
export const SENDING_SEARCH_REQUEST = 'SENDING_SEARCH_REQUEST';
