// General
export const SET_PERIOD = 'SET_PERIOD';

// Error
export const ADD_MOST_RECENT_ERROR = 'ADD_MOST_RECENT_ERROR';
export const REMOVE_LAST_ERROR = 'REMOVE_LAST_ERROR';

// Match Search
export const SET_MATCH_RESULTS = 'SET_MATCH_RESULTS';
export const SET_MATCH_HEADERS = 'SET_MATCH_HEADERS';
export const SENDING_MATCH_REQUEST = 'SENDING_MATCH_REQUEST';
export const SET_MATCH_QUERY = 'SET_MATCH_QUERY';
export const SET_MATCH_ERROR_MESSAGE = 'SET_MATCH_ERROR_MESSAGE';

// Range Search
export const SET_RANGE_RESULTS = 'SET_RANGE_RESULTS';
export const SET_RANGE_HEADERS = 'SET_RANGE_HEADERS';
export const SENDING_RANGE_REQUEST = 'SENDING_RANGE_REQUEST';
export const SET_RANGE_QUERY = 'SET_RANGE_QUERY';
export const SET_RANGE_ERROR_MESSAGE = 'SET_RANGE_ERROR_MESSAGE';

// UBRN Search
export const SET_UBRN_RESULTS = 'SET_UBRN_RESULTS';
export const SET_UBRN_HEADERS = 'SET_UBRN_HEADERS';
export const SENDING_UBRN_REQUEST = 'SENDING_UBRN_REQUEST';
export const SET_UBRN_QUERY = 'SET_UBRN_QUERY';
export const SET_UBRN_ERROR_MESSAGE = 'SET_UBRN_ERROR_MESSAGE';

